name: PR-Agent (self-hosted + EXAONE, Windows)

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
    paths: ['**/*.py']
  issue_comment:
    types: [created, edited]

jobs:
  review:
    runs-on: self-hosted
    defaults:
      run:
        shell: pwsh
    permissions:
      issues: write
      pull-requests: write
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Sanity check Ollama
        run: |
          curl.exe -fsS http://localhost:11434/api/tags

      - name: Ensure EXAONE 3.5 model is present
        run: |
          Invoke-RestMethod -Uri http://localhost:11434/api/pull `
            -Method POST -ContentType 'application/json' `
            -Body '{"name":"exaone3.5:7.8b"}'

          $ok = $false
          for ($i=0; $i -lt 60; $i++) {
            try {
              $resp = Invoke-RestMethod -Uri http://localhost:11434/api/tags -Method GET
              if ($resp.models.name -contains 'exaone3.5:7.8b') { $ok = $true; break }
            } catch { }
            Start-Sleep -Seconds 5
          }
          if (-not $ok) { throw "exaone3.5:7.8b 모델이 5분 내 준비되지 않았습니다." }

      - name: Run PR-Agent
        uses: qodo-ai/pr-agent@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          config.model: "ollama/exaone3.5:7.8b"
          OLLAMA.API_BASE: "http://localhost:11434"
          github_action_config.auto_review: "true"
          github_action_config.auto_describe: "true"
