name: PR-Agent (Windows self-hosted + Ollama EXAONE)

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
    paths: ['**/*.py']
  issue_comment:
    types: [created, edited]

jobs:
  pr_agent:
    runs-on: [self-hosted, Windows]
    # PR 코멘트일 때: PR에 달린 코멘트 + 사람이 쓴 것 + 우리가 지원하는 슬래시 명령만 실행
    if: >
      (github.event_name == 'pull_request') ||
      (github.event_name == 'issue_comment' &&
       github.event.issue.pull_request &&
       github.event.comment.user.type != 'Bot' &&
       (startsWith(github.event.comment.body, '/review') ||
        startsWith(github.event.comment.body, '/describe') ||
        startsWith(github.event.comment.body, '/improve') ||
        startsWith(github.event.comment.body, '/ask') ||
        startsWith(github.event.comment.body, '/update_changelog') ||
        startsWith(github.event.comment.body, '/help_docs')))
    defaults:
      run:
        shell: powershell
    permissions:
      issues: write
      pull-requests: write
      contents: write

    steps:
      - uses: actions/checkout@v4

      # 0) 이벤트별 PR URL/번호 + 실행 커맨드/인자 파싱
      - name: Set PR context & command
        env:
          REPO: ${{ github.repository }}
          EVT: ${{ github.event_name }}
          PR_NUM_PR: ${{ github.event.pull_request.number }}
          PR_NUM_CM: ${{ github.event.issue.number }}
          CMDBODY: ${{ github.event.comment.body }}
        run: |
          # PR 번호/URL
          $prNum = if ($Env:EVT -eq 'pull_request') { $Env:PR_NUM_PR } else { $Env:PR_NUM_CM }
          if (-not $prNum) { throw "PR number not found for event $($Env:EVT)" }
          "PR_NUMBER=$prNum" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "PR_URL=https://github.com/$($Env:REPO)/pull/$prNum" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

          # 커맨드/인자 파싱 (코멘트 이벤트인 경우에만)
          $cmd = 'review'
          $arg = $null
          if ($Env:EVT -eq 'issue_comment') {
            $body = ($Env:CMDBODY ?? '').Trim()

            # 맨 앞 슬래시 커맨드와 나머지를 분리
            if ($body -match '^\s*/([a-zA-Z_]+)\s*(.*)$') {
              $cmdRaw = $matches[1].ToLower()
              $rest   = $matches[2].Trim()

              # 지원 커맨드만 허용
              switch ($cmdRaw) {
                'review'            { $cmd = 'review' }
                'describe'          { $cmd = 'describe' }
                'improve'           { $cmd = 'improve' }              # /improve  (코드 개선) :contentReference[oaicite:1]{index=1}
                'ask'               { $cmd = 'ask';         $arg = $rest.Trim('"') }  # /ask "질문" :contentReference[oaicite:2]{index=2}
                'update_changelog'  { $cmd = 'update_changelog' }      # /update_changelog (CHANGELOG 자동 갱신) :contentReference[oaicite:3]{index=3}
                'help_docs'         { $cmd = 'help_docs';   $arg = $rest.Trim('"') }  # /help_docs "질문" (레포 /docs 기본) :contentReference[oaicite:4]{index=4}
                default             { $cmd = 'review' }
              }
            }
          }

          "PR_AGENT_COMMAND=$cmd" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          if ($arg) { "PR_AGENT_ARG=$arg" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append }

      # 1) Ollama(로컬) 확인 + EXAONE 3.5 모델 준비
      - name: Ensure Ollama (reviewOllama) is running
        run: |
          $running = docker ps --format '{{.Names}}' | Select-String -Pattern '^reviewOllama$'
          if (-not $running) {
            $exists = docker ps -a --format '{{.Names}}' | Select-String -Pattern '^reviewOllama$'
            if (-not $exists) {
              docker run -d --name reviewOllama --restart unless-stopped `
                -p 11434:11434 `
                -e OLLAMA_CONTEXT_LENGTH=8000 `
                -v ollama_models:/root/.ollama `
                ollama/ollama:latest | Out-Null
            } else {
              docker start reviewOllama | Out-Null
            }
          }
          Invoke-RestMethod http://localhost:11434/api/tags -Method GET | Out-Null

      - name: Pull EXAONE 3.5 model (first time only)
        run: |
          Invoke-RestMethod http://localhost:11434/api/pull -Method POST -ContentType 'application/json' `
            -Body '{"name":"exaone3.5:7.8b"}' | Out-Null
          $ok = $false
          for ($i=0; $i -lt 60; $i++) {
            try {
              $resp = Invoke-RestMethod http://localhost:11434/api/tags -Method GET
              if ($resp.models.name -contains 'exaone3.5:7.8b') { $ok = $true; break }
            } catch {}
            Start-Sleep 5
          }
          if (-not $ok) { throw "exaone3.5:7.8b 모델이 5분 내 준비되지 않았습니다." }

      # 2) PR-Agent 실행 (review/describe/improve/ask/update_changelog/help_docs 공용)
      - name: Run PR-Agent (${{ env.PR_AGENT_COMMAND }})
        env:
          # 한국어 고정
          CONFIG__RESPONSE_LANGUAGE: ko-KR
          PR_REVIEWER__LANGUAGE: ko

          # Ollama(호스트) + 모델/토큰/폴백
          OLLAMA__API_BASE: http://host.docker.internal:11434
          CONFIG__ACTIVE_PROVIDER: ollama
          CONFIG__MODEL: ollama/exaone3.5:7.8b
          CONFIG__CUSTOM_MODEL_MAX_TOKENS: 8000
          CONFIG__FALLBACK_MODELS: "[]"
          CONFIG__LOG_LEVEL: DEBUG

          # GitHub 권한
          GITHUB__USER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $args = @("run","--rm")
          $envs = @(
            "OLLAMA__API_BASE=$($Env:OLLAMA__API_BASE)",
            "CONFIG__ACTIVE_PROVIDER=$($Env:CONFIG__ACTIVE_PROVIDER)",
            "CONFIG__MODEL=$($Env:CONFIG__MODEL)",
            "CONFIG__CUSTOM_MODEL_MAX_TOKENS=$($Env:CONFIG__CUSTOM_MODEL_MAX_TOKENS)",
            "CONFIG__FALLBACK_MODELS=$($Env:CONFIG__FALLBACK_MODELS)",
            "CONFIG__RESPONSE_LANGUAGE=$($Env:CONFIG__RESPONSE_LANGUAGE)",
            "PR_REVIEWER__LANGUAGE=$($Env:PR_REVIEWER__LANGUAGE)",
            "CONFIG__LOG_LEVEL=$($Env:CONFIG__LOG_LEVEL)",
            "GITHUB__USER_TOKEN=$($Env:GITHUB__USER_TOKEN)"
          )
          foreach ($e in $envs) { $args += @("-e",$e) }

          # docker run codiumai/pr-agent:latest --pr_url <URL> <command> [arg?]
          $args += @("codiumai/pr-agent:latest","--pr_url","$Env:PR_URL","$Env:PR_AGENT_COMMAND")
          if ($Env:PR_AGENT_ARG) { $args += @("$Env:PR_AGENT_ARG") }  # /ask, /help_docs 질문 전달

          & docker @args
